###
### Base:
###   * https://github.com/vvakame/docker-review/blob/master/review-2.5/Dockerfile
###
### Changes:
###   * use base image 'ubuntu:18.04' instead of 'debian:stretch-slim'
###   * remove maintainer label and add description label
###   * install 'texlive-xetex'
###   * install 'texlive-lang-cjk' and 'texlive-lang-chinese'
###   * install 'texlive-fonts-extra' package (necessary for 'beramono.sty')
###   * install 'texlive-generic-recommended' package (necessary for 'ulem.sty')
###   * install Noto font from standard package, not backport package
###   * no need to install Noto font, because already installed on Ubuntu18!
###   * use 'gem install -N' instead of 'gem install --no-rdoc --no-ri'
###   * add 'gem install combine_pdf' (necessary for 'rake pdf:nombre')
###

FROM ubuntu:18.04
LABEL description="for reviewstarter with Re:VIEW 2.5"

ENV REVIEW_VERSION 2.5.0
ENV REVIEW_PEG_VERSION 0.2.2
ENV NODEJS_VERSION 9

ENV LANG en_US.UTF-8

# setup
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      locales git-core curl ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen en_US.UTF-8 && update-locale en_US.UTF-8

# install Re:VIEW environment
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      texlive texlive-xetex \
      texlive-lang-english texlive-lang-cjk texlive-lang-japanese texlive-lang-chinese \
      texlive-latex-recommended texlive-latex-extra \
      texlive-fonts-recommended texlive-fonts-extra texlive-font-utils \
      lmodern fonts-lmodern tex-gyre fonts-texgyre texlive-pictures \
      texlive-generic-recommended \
      fonts-noto fonts-noto-cjk fonts-noto-cjk-extra fonts-noto-color-emoji \
      ghostscript gsfonts zip ruby-zip ruby-nokogiri mecab ruby-mecab mecab-ipadic-utf8 poppler-data cm-super \
      graphviz gnuplot python-blockdiag python-aafigure && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
## if you want to use ipa font instead of noto font, use this settings
# RUN kanji-config-updmap ipaex

# setup Re:VIEW
RUN gem install -N bundler rake && \
    gem install -N combine_pdf && \
    gem install -N review -v "$REVIEW_VERSION" && \
    gem install -N review-peg -v "$REVIEW_PEG_VERSION"

# install node.js environment
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      gnupg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash - 
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    npm install -g yarn

## install font map of noto for dvipdfmx
COPY noto/ /usr/share/texlive/texmf-dist/fonts/map/dvipdfmx/ptex-fontmaps/noto/

## use noto for uplatex
RUN texhash && kanji-config-updmap-sys noto

## set cache folder to work folder (disabled by default)
# RUN mkdir -p /etc/texmf/texmf.d && echo "TEXMFVAR=/work/.texmf-var" > /etc/texmf/texmf.d/99local.cnf
